//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BMW_AppService.Empservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IEmployeeService", Namespace="http://tempuri.org/")]
    public partial class IEmployeeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IEmployeeService() {
            this.Url = global::BMW_AppService.Properties.Settings.Default.BMW_AppService_Empservice_IEmployeeService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestServicesCompletedEventHandler TestServicesCompleted;
        
        /// <remarks/>
        public event XmlMethodCompletedEventHandler XmlMethodCompleted;
        
        /// <remarks/>
        public event GetAllEmployeeCompletedEventHandler GetAllEmployeeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEmployeeService/TestServices", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TestServices([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string message) {
            object[] results = this.Invoke("TestServices", new object[] {
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestServicesAsync(string message) {
            this.TestServicesAsync(message, null);
        }
        
        /// <remarks/>
        public void TestServicesAsync(string message, object userState) {
            if ((this.TestServicesOperationCompleted == null)) {
                this.TestServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestServicesOperationCompleted);
            }
            this.InvokeAsync("TestServices", new object[] {
                        message}, this.TestServicesOperationCompleted, userState);
        }
        
        private void OnTestServicesOperationCompleted(object arg) {
            if ((this.TestServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestServicesCompleted(this, new TestServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEmployeeService/XmlMethod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void XmlMethod([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Xml.XmlElement xml) {
            this.Invoke("XmlMethod", new object[] {
                        xml});
        }
        
        /// <remarks/>
        public void XmlMethodAsync(System.Xml.XmlElement xml) {
            this.XmlMethodAsync(xml, null);
        }
        
        /// <remarks/>
        public void XmlMethodAsync(System.Xml.XmlElement xml, object userState) {
            if ((this.XmlMethodOperationCompleted == null)) {
                this.XmlMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlMethodOperationCompleted);
            }
            this.InvokeAsync("XmlMethod", new object[] {
                        xml}, this.XmlMethodOperationCompleted, userState);
        }
        
        private void OnXmlMethodOperationCompleted(object arg) {
            if ((this.XmlMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlMethodCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IEmployeeService/GetAllEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/CloudDataService.Models")]
        public EmployeeModel[] GetAllEmployee() {
            object[] results = this.Invoke("GetAllEmployee", new object[0]);
            return ((EmployeeModel[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeeAsync() {
            this.GetAllEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeeAsync(object userState) {
            if ((this.GetAllEmployeeOperationCompleted == null)) {
                this.GetAllEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeeOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployee", new object[0], this.GetAllEmployeeOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeeOperationCompleted(object arg) {
            if ((this.GetAllEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeeCompleted(this, new GetAllEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CloudDataService.Models")]
    public partial class EmployeeModel {
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private DepartmentModel departmentField;
        
        private string empCodeField;
        
        private string empNameField;
        
        private string genderField;
        
        private System.DateTime joinDateField;
        
        private bool joinDateFieldSpecified;
        
        private string lastUpdateByField;
        
        private System.DateTime lastUpdateDateField;
        
        private bool lastUpdateDateFieldSpecified;
        
        private string positionField;
        
        private string preNameField;
        
        private decimal salaryField;
        
        private bool salaryFieldSpecified;
        
        private string surnameField;
        
        private string telephoneNoField;
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DepartmentModel Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpCode {
            get {
                return this.empCodeField;
            }
            set {
                this.empCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmpName {
            get {
                return this.empNameField;
            }
            set {
                this.empNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JoinDateSpecified {
            get {
                return this.joinDateFieldSpecified;
            }
            set {
                this.joinDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastUpdateBy {
            get {
                return this.lastUpdateByField;
            }
            set {
                this.lastUpdateByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastUpdateDateSpecified {
            get {
                return this.lastUpdateDateFieldSpecified;
            }
            set {
                this.lastUpdateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PreName {
            get {
                return this.preNameField;
            }
            set {
                this.preNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SalarySpecified {
            get {
                return this.salaryFieldSpecified;
            }
            set {
                this.salaryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TelephoneNo {
            get {
                return this.telephoneNoField;
            }
            set {
                this.telephoneNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CloudDataService.Models")]
    public partial class DepartmentModel {
        
        private string departmantCodeField;
        
        private string departmentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartmantCode {
            get {
                return this.departmantCodeField;
            }
            set {
                this.departmantCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DepartmentName {
            get {
                return this.departmentNameField;
            }
            set {
                this.departmentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TestServicesCompletedEventHandler(object sender, TestServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void XmlMethodCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetAllEmployeeCompletedEventHandler(object sender, GetAllEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmployeeModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmployeeModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591